sudo: false
language: python
python:
 - "3.5"
 - "3.6"
 - "3.7-dev"

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source traio -m py.test
  - coverage report -m

after_success:
  - coveralls
